// India — All 28 States + 8 Union Territories with areas
const INDIA_LOCATIONS = {
  "Andhra Pradesh":["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Tirupati","Rajahmundry","Kakinada","Kadapa","Anantapur","Eluru","Ongole","Chittoor","Machilipatnam"],
  "Arunachal Pradesh":["Itanagar","Naharlagun","Pasighat","Tawang","Ziro","Bomdila","Along","Tezu","Roing","Daporijo"],
  "Assam":["Guwahati","Silchar","Dibrugarh","Jorhat","Nagaon","Tinsukia","Tezpur","Bongaigaon","Karimganj","Dhubri","Sivasagar","Goalpara"],
  "Bihar":["Patna","Gaya","Bhagalpur","Muzaffarpur","Darbhanga","Purnia","Ara","Begusarai","Katihar","Munger","Chapra","Samastipur","Hajipur","Bettiah"],
  "Chhattisgarh":["Raipur","Bhilai","Bilaspur","Korba","Durg","Rajnandgaon","Raigarh","Jagdalpur","Ambikapur","Mahasamund"],
  "Goa":["Panaji","Margao","Vasco da Gama","Mapusa","Ponda","Bicholim","Curchorem","Sanquelim","Canacona","Quepem"],
  "Gujarat":["Ahmedabad","Surat","Vadodara","Rajkot","Gandhinagar","Bhavnagar","Jamnagar","Junagadh","Anand","Navsari","Morbi","Mehsana","Bharuch","Gandhidham","Porbandar"],
  "Haryana":["Gurugram","Faridabad","Panipat","Ambala","Karnal","Hisar","Rohtak","Sonipat","Panchkula","Yamunanagar","Rewari","Bhiwani","Sirsa","Jhajjar"],
  "Himachal Pradesh":["Shimla","Manali","Dharamshala","Mandi","Solan","Kullu","Bilaspur","Hamirpur","Nahan","Palampur","Chamba","Una"],
  "Jharkhand":["Ranchi","Jamshedpur","Dhanbad","Bokaro","Deoghar","Hazaribagh","Giridih","Ramgarh","Phusro","Medininagar"],
  "Karnataka":["Bangalore","Mysore","Hubli","Mangalore","Belgaum","Gulbarga","Davangere","Shimoga","Tumkur","Udupi","Bellary","Bijapur","Raichur","Hassan","Mandya"],
  "Kerala":["Thiruvananthapuram","Kochi","Kozhikode","Thrissur","Kollam","Kannur","Alappuzha","Kottayam","Palakkad","Malappuram","Munnar","Wayanad"],
  "Madhya Pradesh":["Bhopal","Indore","Jabalpur","Gwalior","Ujjain","Sagar","Satna","Rewa","Ratlam","Dewas","Burhanpur","Morena","Chhindwara","Singrauli"],
  "Maharashtra":["Mumbai","Pune","Nagpur","Nashik","Thane","Aurangabad","Navi Mumbai","Solapur","Kolhapur","Amravati","Sangli","Akola","Latur","Jalgaon","Ahmednagar","Chandrapur","Parbhani","Ratnagiri"],
  "Manipur":["Imphal","Thoubal","Bishnupur","Churachandpur","Kakching","Senapati","Ukhrul","Tamenglong","Chandel","Jiribam"],
  "Meghalaya":["Shillong","Tura","Jowai","Nongstoin","Williamnagar","Baghmara","Resubelpara","Nongpoh","Ampati","Mairang"],
  "Mizoram":["Aizawl","Lunglei","Champhai","Serchhip","Kolasib","Lawngtlai","Saiha","Mamit","Hnahthial","Khawzawl"],
  "Nagaland":["Kohima","Dimapur","Mokokchung","Tuensang","Wokha","Zunheboto","Mon","Phek","Peren","Kiphire"],
  "Odisha":["Bhubaneswar","Cuttack","Rourkela","Berhampur","Sambalpur","Puri","Balasore","Baripada","Bhadrak","Jharsuguda","Jeypore","Angul"],
  "Punjab":["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Mohali","Pathankot","Hoshiarpur","Batala","Moga","Abohar","Malerkotla","Khanna","Phagwara"],
  "Rajasthan":["Jaipur","Jodhpur","Udaipur","Kota","Ajmer","Bikaner","Alwar","Bhilwara","Sikar","Bharatpur","Pali","Sri Ganganagar","Tonk","Kishangarh","Beawar"],
  "Sikkim":["Gangtok","Namchi","Gyalshing","Mangan","Rangpo","Singtam","Jorethang","Ravangla","Pelling","Lachung"],
  "Tamil Nadu":["Chennai","Coimbatore","Madurai","Salem","Trichy","Tirunelveli","Erode","Vellore","Thanjavur","Tiruppur","Dindigul","Hosur","Thoothukudi","Nagercoil","Kanchipuram","Karur"],
  "Telangana":["Hyderabad","Warangal","Karimnagar","Nizamabad","Khammam","Ramagundam","Mahbubnagar","Nalgonda","Adilabad","Siddipet","Suryapet","HITEC City","Gachibowli","Kukatpally","Secunderabad"],
  "Tripura":["Agartala","Udaipur","Dharmanagar","Kailashahar","Belonia","Ambassa","Khowai","Sabroom","Amarpur","Sonamura"],
  "Uttar Pradesh":["Lucknow","Noida","Agra","Varanasi","Kanpur","Ghaziabad","Meerut","Allahabad","Bareilly","Aligarh","Moradabad","Gorakhpur","Firozabad","Jhansi","Mathura","Saharanpur","Greater Noida","Faizabad"],
  "Uttarakhand":["Dehradun","Haridwar","Rishikesh","Haldwani","Roorkee","Kashipur","Rudrapur","Nainital","Mussoorie","Pithoragarh","Almora","Kotdwar"],
  "West Bengal":["Kolkata","Howrah","Durgapur","Siliguri","Asansol","Bardhaman","Kharagpur","Haldia","Malda","Baharampur","Salt Lake","Raiganj","Krishnanagar","Darjeeling"],
  "Delhi (NCT)":["Connaught Place","Dwarka","Saket","Karol Bagh","Lajpat Nagar","Chandni Chowk","Rohini","Pitampura","Janakpuri","Nehru Place","Rajouri Garden","Greater Kailash","Defence Colony","Hauz Khas","Preet Vihar","Vasant Kunj"],
  "Chandigarh":["Sector 17","Sector 22","Sector 35","Sector 43","Industrial Area","Manimajra","IT Park","Elante Area","Sector 9","Sector 26"],
  "Jammu & Kashmir":["Srinagar","Jammu","Anantnag","Baramulla","Sopore","Kathua","Udhampur","Leh","Kargil","Rajouri","Poonch","Kupwara"],
  "Ladakh":["Leh","Kargil","Diskit","Padum","Nyoma","Hanle","Tangtse","Dras","Sankoo","Zanskar"],
  "Puducherry":["Puducherry Town","Ozhukarai","Villianur","Karaikal","Mahe","Yanam","Lawspet","Mudaliarpet","Reddiarpalayam","Bahour"],
  "Andaman & Nicobar":["Port Blair","Car Nicobar","Mayabunder","Diglipur","Rangat","Havelock Island","Neil Island","Campbell Bay","Long Island","Baratang"],
  "Dadra Nagar Haveli & Daman Diu":["Silvassa","Daman","Diu","Amli","Naroli","Khanvel","Dunetha","Vapi Border","Marwad","Samarvarni"],
  "Lakshadweep":["Kavaratti","Agatti","Minicoy","Amini","Andrott","Kalpeni","Kadmat","Chetlat","Bitra","Kiltan"]
};
window.INDIA_LOCATIONS = INDIA_LOCATIONS;
